### ISSUE TITLE
pen quit after 60 trials connecting to xwc api

### ISSUE THREAD

**Issue by iamif3000** [penguintop/penguin#27]
If we deploy thousands of pen nodes, this behavior may cause trouble(we have to rerestart all the pen nodes).
So please change this behavior to retry forever.

**Comment by Kevin-Busquets** [comment]
Thanks for your kind issuing, we are planning to solve the issue and fix it as soon as possible.

**Comment by Kevin-Busquets** [comment]
It was solved
